<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GridStack.Blazor.Demo\GridStack.Blazor.Demo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack-all.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack-all.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack.min.css" />
  </ItemGroup>

</Project>
