<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.3" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GridStack.Blazor.Demo\GridStack.Blazor.Demo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\AppWidget.razor" />
      <_ContentIncludedByDefault Remove="Components\DeleteButton.razor" />
      <_ContentIncludedByDefault Remove="Components\GraphAppWidget.razor" />
      <_ContentIncludedByDefault Remove="Components\GridComponent.razor" />
      <_ContentIncludedByDefault Remove="Components\ValueAppWidget.razor" />
      <_ContentIncludedByDefault Remove="Layout\MainLayout.razor" />
      <_ContentIncludedByDefault Remove="Layout\Sidebar.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo1.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo2.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo3.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo4.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo5.razor" />
      <_ContentIncludedByDefault Remove="Pages\Demo6.razor" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack-all.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\gridstack.min.css" />
    </ItemGroup>

</Project>
