<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\GridStack.Blazor\GridStack.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    </ItemGroup>
    
</Project>
